// <auto-generated />
using System;
using MVC_ASP.NET_Core_Learn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_ASP.NET_Core_Learn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_ASP.NET_Core_Learn.Models.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("InterestRate")
                        .HasColumnType("int");

                    b.Property<double?>("InterestRateEarlyClosure")
                        .HasColumnType("float");

                    b.Property<double?>("InterestRateNoEarlyClosure")
                        .HasColumnType("float");

                    b.Property<bool>("Replenishment")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("MVC_ASP.NET_Core_Learn.Models.DepositTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DepositId")
                        .HasColumnType("int");

                    b.Property<int>("NumberMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepositId");

                    b.ToTable("DepositTerm");
                });

            modelBuilder.Entity("MVC_ASP.NET_Core_Learn.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birdthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVC_ASP.NET_Core_Learn.Models.DepositTerm", b =>
                {
                    b.HasOne("MVC_ASP.NET_Core_Learn.Models.Deposit", null)
                        .WithMany("Term")
                        .HasForeignKey("DepositId");
                });

            modelBuilder.Entity("MVC_ASP.NET_Core_Learn.Models.Deposit", b =>
                {
                    b.Navigation("Term");
                });
#pragma warning restore 612, 618
        }
    }
}
